development:
  adapter: postgresql
  database: development_sampleApp
  username: postgres
  password: root
  host: localhost

test:
  adapter: postgresql
  database: test_sampleApp
  username: postgres
  password: root
  host: localhost

production:
  adapter: postgresql
  database: production_sampleApp
  username: postgres
  password: root
  host: localhost